# Render Blueprint configuration
databases:
  - name: youtube-downloader-db
    databaseName: youtube_db
    user: user
    plan: free

services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    # Updated startCommand to use python -m gunicorn and bind to the PORT environment variable
    startCommand: "python -m gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
    regions:
      - oregon
    plan: free
    healthCheckPath: / # Changed from /dashboard to / as main UI is now at root
    autoDeploy: true